#!/bin/bash

current_time=$(date +"%m%d%H%M")

#备份的目录
backup_dir="/backup"

#名字
backup_name="sys$current_time.tar.gz"

#被备份的目录
backuped_dir="/"


str="$backup_dir/*"
sudo rm -rf $str

echo “开始备份”

start_timestamp=$(date +%s)

sudo tar -zcvf "$backup_dir/$backup_name" --exclude=/proc --exclude=/lost+found --exclude=/backup --exclude=/mnt --exclude=/sys --exclude=/media --exclude=/home/xiucong/Desktop/Xilinx "$backuped_dir"

end_timestamp=$(date +%s)

elapsed_time=$((($end_timestamp - $start_timestamp) / 60 ))


echo "备份已完成"
echo "备份文件名: $backup_name"
echo "备份使用时间: ${elapsed_time}min"

